# Generated by Django 6.0 on 2025-12-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_line_alter_connection_distance_connection_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='time',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='connection',
            name='line',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='metro.line'),
            preserve_default=False,
        ),
    ]
