# Generated by Django 6.0 on 2025-12-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0003_connection_time_alter_connection_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='time',
            field=models.IntegerField(default=3),
        ),
    ]
