# Generated by Django 6.0 on 2025-12-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0004_alter_connection_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='time',
        ),
        migrations.AddField(
            model_name='connection',
            name='travel_time',
            field=models.IntegerField(default=3),
        ),
    ]
